apiVersion: app/v1
kind: Deployment
metadata:
  name: posts-yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels: 
        app: posts
    spec:
      containers:
        - name: post
          image: alqamashuja101/posts:0.0.1